# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-community
  labels:
    app: {{ .Release.Name }}-community
  annotations:
    {{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.cloud.provider | default "gke" | eq "gke") }}
    networking.gke.io/load-balancer-type: "External"
    cloud.google.com/load-balancer-type: "External"
    {{- else if and (eq .Values.service.type "LoadBalancer") (.Values.service.cloud.provider | eq "aws") }}
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    {{- else if and (eq .Values.service.type "LoadBalancer") (.Values.service.cloud.provider | eq "azure") }}
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.service.cloud.resourceGroup | default "" }}
    {{- else if and (eq .Values.service.type "LoadBalancer") (not .Values.service.cloud.provider) }}
    # Default LoadBalancer annotations for unspecified cloud provider
    service.kubernetes.io/load-balancer-type: "External"
    {{- end }}
spec:
  type: {{ .Values.service.type }}

  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.global.externalIP }}
  externalTrafficPolicy: Cluster
  {{- end }}
  
  ports:
  {{- if .Values.community.config.community.enableSubpathBasedAccess }}
  - name: subpath
    protocol: TCP
    port: {{ .Values.service.ports.subpath.port }}
    targetPort: {{ .Values.service.ports.subpath.targetPort }}
  {{- else }}
  - name: frontend
    protocol: TCP
    port: {{ .Values.service.ports.frontend.port }}
    targetPort: {{ .Values.service.ports.frontend.targetPort }}
  
  - name: admin
    protocol: TCP
    port: {{ .Values.service.ports.admin.port }}
    targetPort: {{ .Values.service.ports.admin.targetPort }}
  
  - name: backend
    protocol: TCP
    port: {{ .Values.service.ports.backend.port }}
    targetPort: {{ .Values.service.ports.backend.targetPort }}
  {{- end }}

  selector:
    app: {{ .Release.Name }}-community
